name: 'nyc_hvfhs_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'nyc_hvfhs_lakehouse'

vars:
  source_year: 2024
  source_month: 1

model-paths: ["models_nyc"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "logs"

models:
  nyc_hvfhs_lakehouse:
    +materialized: table
