"""
Warehouse API - FastAPI application

CRITICAL BUG FIX APPLIED:
- Use Pydantic QueryRequest model for JSON body (not query param)

Endpoints:
- GET / - Health check
- POST /query - Execute validated SQL query
- GET /recommendations/{user_id} - Get recommendations
- GET /recommendations/stats - Get stats

Author: Data Engineering Team
Date: 2026-07-13
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional, List, Dict, Any
import os
import sys
from pathlib import Path

# Add warehouse to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from warehouse.engine.duckdb_engine import DuckDBEngine
from warehouse.parser.sql_validator import validate_sql
from warehouse.recommendation_store import RecommendationStore


# Pydantic models
class QueryRequest(BaseModel):
    """
    Request body for POST /query
    
    CRITICAL FIX: Use JSON body, not query string parameter
    """
    sql: str
    params: Optional[List] = None


class QueryResponse(BaseModel):
    """Response for SQL queries"""
    columns: List[str]
    rows: List
    row_count: int


class RecommendationResponse(BaseModel):
    """Response for recommendations"""
    user_id: int
    products: List[Dict[str, Any]]
    model_version: str
    generated_at: str


# Initialize FastAPI
app = FastAPI(
    title="Instacart Warehouse API",
    description="Query engine + Recommendation Store",
    version="1.0.0"
)

# Initialize engines (singleton pattern)
print("🚀 Initializing warehouse services...")

engine = DuckDBEngine(
    db_path=os.getenv("DUCKDB_PATH", "warehouse/data/warehouse.db"),
    use_glue_catalog=os.getenv("USE_GLUE_CATALOG", "true").lower() == "true",
    account_id=os.getenv("AWS_ACCOUNT_ID"),
    role_arn=os.getenv("DUCKDB_ROLE_ARN"),
    region=os.getenv("AWS_REGION", "us-east-1")
)

rec_store = RecommendationStore(
    mongo_uri=os.getenv("MONGODB_URI", "mongodb://mongodb:27017"),
    database="instacart_warehouse"
)

print("✅ Warehouse services initialized")


# Health check
@app.get("/")
def health():
    """
    Health check endpoint
    
    Returns service status and configuration
    """
    return {
        "status": "healthy",
        "service": "Instacart Warehouse API",
        "version": "1.0.0",
        "engines": {
            "duckdb": engine.health_check(),
            "recommendations": {
                "total_users": rec_store.count_users()
            }
        }
    }


# Query endpoint
@app.post("/query", response_model=QueryResponse)
def execute_query(request: QueryRequest):
    """
    Execute read-only SQL query
    
    Request body (JSON):
    {
        "sql": "SELECT * FROM glue_catalog.gold.fct_order_products LIMIT 10",
        "params": []  // optional
    }
    
    Security:
    - AST-based validation (sqlglot)
    - Only SELECT/WITH allowed
    - Multi-statement blocked
    """
    # Validate SQL (AST-based, blocks multi-statement and mutations)
    is_valid, message = validate_sql(request.sql)
    
    if not is_valid:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid SQL: {message}"
        )
    
    # Execute query
    try:
        result = engine.execute(request.sql, request.params)
        return QueryResponse(**result)
        
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Query execution failed: {str(e)}"
        )


# Recommendation endpoints
@app.get("/recommendations/{user_id}")
def get_recommendations(user_id: int):
    """
    Get top-N product recommendations for a user
    
    Returns pre-computed recommendations from MongoDB.
    Recommendations generated by ML model (XGBoost reorder prediction).
    
    Example response:
    {
        "user_id": 12345,
        "products": [
            {"product_id": 101, "product_name": "Banana", "score": 0.92},
            {"product_id": 202, "product_name": "Organic Milk", "score": 0.87}
        ],
        "model_version": "xgboost_v1",
        "generated_at": "2026-07-13T10:30:00Z"
    }
    """
    rec = rec_store.get_recommendations(user_id)
    
    if not rec:
        raise HTTPException(
            status_code=404,
            detail=f"No recommendations found for user {user_id}"
        )
    
    return rec


@app.get("/recommendations/stats")
def get_recommendations_stats():
    """
    Get recommendation store statistics
    
    Returns:
    - Total users with recommendations
    - Model version
    - Last generation timestamp
    """
    stats = rec_store.get_stats()
    
    return {
        "total_users": stats.get("total_users", 0),
        "model_version": stats.get("model_version"),
        "last_generated": stats.get("last_generated"),
        "service": "MongoDB Recommendation Store"
    }


# Catalog exploration endpoints
@app.get("/tables/{database}")
def list_tables(database: str = "gold"):
    """
    List tables in a database/schema
    
    Example: GET /tables/gold
    """
    try:
        tables = engine.get_table_list(database)
        return {
            "database": database,
            "tables": tables,
            "count": len(tables)
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to list tables: {str(e)}"
        )


@app.get("/schema/{table_name}")
def get_schema(table_name: str):
    """
    Get schema for a table
    
    Example: GET /schema/glue_catalog.gold.fct_order_products
    """
    try:
        schema = engine.get_table_schema(table_name)
        return {
            "table": table_name,
            "columns": schema
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to get schema: {str(e)}"
        )


# Shutdown handler
@app.on_event("shutdown")
def shutdown_event():
    """Cleanup resources on shutdown"""
    print("🛑 Shutting down warehouse services...")
    engine.close()
    rec_store.close()
    print("✅ Shutdown complete")


if __name__ == "__main__":
    """Run with uvicorn for development"""
    import uvicorn
    
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True
    )
